### ISSUE TITLE
Data Historian not properly launched at install

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#143]
Running the install script seems okay (no message) but in reality the Data Historian is not running and in the log we have this stack trace: 
2020-07-09 16:53:45: START
Jul 09, 2020 4:53:45 PM io.vertx.core.impl.launcher.commands.RunCommand
SEVERE: Failed to create the vert.x instance
java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:
332)
	at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:165)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
	at io.vertx.core.Vertx.vertx(Vertx.java:85)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(Classpat
hHandler.java:113)
	at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareComma
nd.java:278)
	at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java
:192)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:2
49)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommand
Launcher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxComman
dLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxComman
dLauncher.java:346)
	at io.vertx.core.Launcher.main(Launcher.java:45)

**Comment by MiniPlayer** [comment]
This was a documentation problem mainly. We should not install historian as root.
