### ISSUE TITLE
Grafana says no data while we do have data in the specified range

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#152]
We have data injected, the timestamp is okay but grafana keeps saying "no data" with this stack trace in the log
2020-07-21 09:11:04 ERROR Unexpected error : 
(RECIPIENT_FAILURE,-1) Error from server at http://127.0.1.1:8983/solr/historian
: org.apache.solr.search.SyntaxError: Cannot parse ':*': Encountered " ":" ": ""
 at line 1, column 0.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    <TERM> ...
    
	at io.vertx.serviceproxy.HelperUtils.lambda$createHandler$0(HelperUtils.
java:23)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopCo
ntext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEv
entExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-21 09:19:52 ERROR error parsing request
io.vertx.core.json.DecodeException: Failed to decode: Unexpected character ('F' 
(code 70)): was expecting a colon to separate field name and value
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 3, column: 15]
	at io.vertx.core.json.Json.decodeValue(Json.java:190)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl.lambda$static$1(BodyCodecIm
pl.java:41)
	at io.vertx.ext.web.impl.RoutingContextImpl.getBodyAsJson(RoutingContext
Impl.java:278)
	at io.vertx.ext.web.impl.RoutingContextWrapper.getBodyAsJson(RoutingCont
extWrapper.java:234)
	at io.vertx.reactivex.ext.web.RoutingContext.getBodyAsJson(RoutingContex
t.java:323)
	at com.hurence.webapiservice.http.api.grafana.GrafanaHurenceDatasourcePl
uginApiImpl.query(GrafanaHurenceDatasourcePluginApiImpl.java:265)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:231)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingConte
xtImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrappe
r.java:154)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:256)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:231)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingConte
xtImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java
:133)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHand
lerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandle
rImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHan
dlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequest
Impl.java:531)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerReq
uestImpl.java:517)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServer
Connection.java:175)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xSe
rverConnection.java:162)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xSe
rverConnection.java:139)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173
)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:352)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.jav
a:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHan
dler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Defau
ltChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

Seems to be a parsing error.

**Comment by MiniPlayer** [comment]
Can you please join the query provoking this response ?
