### ISSUE TITLE
gateway throws an error when querying a metric containing a space

### ISSUE THREAD

**Issue by oalam** [Hurence/historian#79]
xception: --> http://localhost:8983/solr/historian:java.util.concurrent.ExecutionException: java.io.IOException: --> http://10.20.20.97:7574/solr/historian_shard2_replica_n2/:no field name specified in query and no default specified via 'df' param
	at org.apache.solr.client.solrj.io.stream.SolrStream.read(SolrStream.java:215)
	at com.hurence.webapiservice.historian.impl.SolrHistorianServiceImpl.getNumberOfPointsByMetricInRequest(SolrHistorianServiceImpl.java:582)
	at com.hurence.webapiservice.historian.impl.SolrHistorianServiceImpl.lambda$getTimeSeries$10(SolrHistorianServiceImpl.java:347)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
4012585 [vert.x-eventloop-thread-3] ERROR com.hurence.webapiservice.http.grafana.GrafanaApiImpl.lambda$query$4(GrafanaApiImpl.java:106) - Unexpected error :

**Comment by MiniPlayer** [comment]
Should be fixed now with commit c5ee50b9a5b11215fe20a4654619fdedf1984e7b
